version: 2.1

#jobs:
#  build:
#    docker:
#      - image: "debian:stretch"
#    steps:
#      - checkout
#      - run:
#          name: Installing SUDO
#          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
#      - run:
#          name: Installing GCC
#          command: 'apt-get update && apt-get install -y gcc g++'
#      - run:
#          name: Install CMAKE
#          command: 'apt-get update && sudo apt-get install -y cmake'          
#      - run:
#          name: Install Curl
#          command: 'apt-get update && sudo apt-get install -y curl'          
#      - run:
#          name: Install Unzip
#          command: 'apt-get update && sudo apt-get install -y unzip'
#      - run:
#          name: Download build-wrapper
#          command: curl 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper-linux-x86.zip
#      - run:
#          name: Unzip build-wrapper
#          command: unzip build-wrapper-linux-x86.zip
#      - run:
#          name: Creating Build Files
#          command: 'cmake -H. -Bbuild'
#      - run:
#          name: Creating Binary Files
#          command: 'build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory cmake --build build'
#      - sonarcloud/scan

jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:          
          name: Download build-wrapper
          command: curl 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper-linux-x86.zip
      - run:
          name: Unzip build-wrapper
          command: unzip build-wrapper-linux-x86.zip
      - run: 
          name: Create build directory
          command: mkdir -p build && cd build          
      - run: 
          name: Build
          command: 'build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory g++ -o main main.cpp -std=c++17'
      - run: ./main
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
